syntax on " シンタックス
filetype plugin on " ファイルタイププラグイン
colorscheme jellybeans

set autoindent " オートインデント
set number " 行番号表示
set list
set listchars=trail:-

" netrw
let g:netrw_liststyle = 3

" タブインデント
set expandtab      " tabをスペースに置き換えない
set tabstop=2      " tabをスペース何文字分で表示するかの指定
set shiftwidth=2   " オートインデント時に挿入されるスペース文字数
set softtabstop=2  " tabキーで挿入されるスペース文字数

" 保存時に行末の空白を除去するコマンド
command TrimTrailingBlank %s/\s\+$//ge
augroup TrimTrailingBlankSpace
  autocmd!
  autocmd BufWritePre * :TrimTrailingBlank"
augroup END

" IME切り替えの待ち時間を短くする
set ttimeoutlen=1

" for mac
if has('mac') && filereadable(expand('~/.vim/vimrc.mac'))
  source ~/.vim/vimrc.mac
" for unix
elseif has('unix') && filereadable(expand('~/.vim/vimrc.unix'))
  source ~/.vim/vimrc.unix
endif

" for local
if filereadable(expand('~/.vim/vimrc.local'))
  source ~/.vim/vimrc.local
endif
