#!/usr/bin/env bash

BIN_DIR=$(cd $(dirname $0); pwd)/../bin
echo $(dirname $BIN_DIR)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "${OS}" = "darwin" ]; then
  OS="macOS"
fi
ARCH=$(uname -m)
if [ "${ARCH}" = "x86_64" ]; then
  ARCH="amd64"
fi
DL_URL=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | ${BIN_DIR}/gojq -r ".assets[] | select(.name | test(\"${OS}\") and test(\"${ARCH}\")) | .browser_download_url")
ARCHIVE_FILE=$(basename ${DL_URL})
WORK_DIR=/tmp/dotfiles/${USER}/gh

mkdir -p ${WORK_DIR}
wget ${DL_URL} -O ${WORK_DIR}/${ARCHIVE_FILE}
${BIN_DIR}/arc -strip-components 2 unarchive ${WORK_DIR}/${ARCHIVE_FILE} ${WORK_DIR}
mv ${WORK_DIR}/gh ${BIN_DIR}/gh
rm -rf ${WORK_DIR}
