# include .zshrc.antigen
[[ -f ${ZDOTDIR}/zshrc.antigen ]] && source ${ZDOTDIR}/zshrc.antigen

# zsh
## history
export HISTFILE="${ZDOTDIR}/history"
export HISTSIZE=100000
export SAVEHIST=${HISTSIZE}

## fpath functions
if [[ -d ${ZDOTDIR}/functions ]]; then
  export FPATH="${ZDOTDIR}/functions:$FPATH"
fi

## oh-my-zsh
export DISABLE_AUTO_TITLE=true



# functions
function excutable() {
  type "$1" &> /dev/null;
}

# environment variables
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"

# no create core dump file
ulimit -c 0

# path .bin
export PATH="${HOME}/.bin:${PATH}"

# go
if excutable go && [[ -d "${HOME}/work" ]]; then
  export GOPATH="${HOME}/work"
  export PATH="${GOPATH}/bin:${PATH}"
fi

# git/diff-highlight
#
## for mac
if [[ -d /usr/local/share/git-core/contrib/diff-highlight ]]; then
  export PATH=${PATH}:/usr/local/share/git-core/contrib/diff-highlight
#
## for arch
elif [[ -d /usr/share/git/diff-highlight ]]; then
  export PATH=$PATH:/usr/share/git/diff-highlight
#
## for debian or ubuntu
elif [[ -d /usr/share/doc/git/contrib/diff-highlight ]]; then
  export PATH=${PATH}:/usr/share/doc/git/contrib/diff-highlight
fi

# direnv
if excutable direnv; then
  export DIRENV_WARN_TIMEOUT=100s
  eval "$(direnv hook zsh)"
fi

# alias
#
## ls
if excutable ls; then
  alias ll="ls -l"
fi
#
## vim
if excutable vim; then
  alias vi="vim"
fi
#
## grep
if excutable grep; then
  alias grep="grep -I --color=auto"
  # for grep's glob
  setopt nonomatch
fi
#
## jq
if excutable jq; then
  alias jq="jq -C"
fi
#
## tmux
if excutable tmux; then
  export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
  if "${OSTYPE}" =~ ^darwin*; then
    alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf -2 -u"
  else
    alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf"
  fi
fi

# less
export LESS="-R -F -X"
if excutable less && excutable source-highlight-esc.sh; then
  export LESSOPEN="| source-highlight-esc.sh %s"
fi

# colordiff
if excutable colordiff; then
  alias diff="colordiff"
fi

# ansible
if excutable ansible; then
  export ANSIBLE_NOCOWS=1
fi

# nproc
if ! excutable nproc && excutable sysctl; then
  alias nproc='sysctl -n hw.physicalcpu'
fi

# make
if excutable make; then
  export MAKEFLAGS="-j$(nproc)"
fi

# select-history and select-path
#
## fzf
if excutable fzf-tmux ]]; then
  # historical search with peco binded to ^r
  function select-history-fzf() {
    # historyを番号なし、逆順、最初から表示。
    # 順番を保持して重複を削除。
    # カーソルの左側の文字列をクエリにしてpecoを起動
    # \nを改行に変換
    BUFFER="$(\history -nr 1 | awk '!a[$0]++' | fzf-tmux --query "${LBUFFER}" --prompt 'HISTORY>' | sed 's/\\n/\n/')"
    # カーソルを文末に移動
    CURSOR=${#BUFFER}
    # refresh
    zle -R -c
  }
  zle -N select-history-fzf
  bindkey '^r' select-history-fzf

  # path selection with peco binded to ^f
  function select-path-fzf() {
    local filepath="$(find . | grep -v '/\.' | fzf-tmux --prompt 'PATH>')"
    [ -z "${filepath}" ] && return
    if [ -n "${LBUFFER}" ]; then
      BUFFER="${LBUFFER}${filepath}"
    else
      if [ -d "${filepath}" ]; then
        BUFFER="cd ${filepath}"
      elif [ -f "${filepath}" ]; then
        BUFFER="${EDITOR} ${filepath}"
      fi
    fi
    CURSOR=${#BUFFER}
  }

  zle -N select-path-fzf
  # Ctrl+f で起動
  bindkey '^f' select-path-fzf
#
## peco
elif excutable peco; then
  # historical search with peco binded to ^r
  function select-history-peco() {
    # historyを番号なし、逆順、最初から表示。
    # 順番を保持して重複を削除。
    # カーソルの左側の文字列をクエリにしてpecoを起動
    # \nを改行に変換
    BUFFER="$(\history -nr 1 | awk '!a[$0]++' | peco --query "${LBUFFER}" | sed 's/\\n/\n/')"
    # カーソルを文末に移動
    CURSOR=${#BUFFER}
    # refresh
    zle -R -c
  }
  zle -N select-history-peco
  # Ctrl+f
  bindkey '^r' select-history-peco

  # path selection with peco binded to ^f
  function select-path-peco() {
    local filepath="$(find . | grep -v '/\.' | peco --prompt 'PATH>')"
    [ -z "${filepath}" ] && return
    if [ -n "${LBUFFER}" ]; then
      BUFFER="${LBUFFER}${filepath}"
    else
      if [ -d "${filepath}" ]; then
        BUFFER="cd ${filepath}"
      elif [ -f "${filepath}" ]; then
        BUFFER="${EDITOR} ${filepath}"
      fi
    fi
    CURSOR=${#BUFFER}
  }
  zle -N select-path-peco
  # Ctrl+f
  bindkey '^f' select-path-peco
fi

# gg
#
## fzf
if excutable ghq && excutable fzf-tmux; then
  alias gg='cd $(ghq list -p | fzf-tmux)'
#
## peco
elif excutable ghq && excutable peco; then
  alias gg='cd $(ghq list -p | peco)'
fi

# historica backward/forward search with linehead string binded to ^p/^n
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# update compinit
autoload -U compinit
compinit

# include .zshrc.local
[[ -f ${ZDOTDIR}/zshrc.local ]] && source ${ZDOTDIR}/zshrc.local
