# include .zshrc.antigen
[[ -f ${ZDOTDIR}/zshrc.antigen ]] && source ${ZDOTDIR}/zshrc.antigen

# variables
_ostype=$(uname -s | tr '[:upper:]' '[:lower:]')

# include ostype files
[[ -f ${ZDOTDIR}/zshrc.${_ostype} ]] && source ${ZDOTDIR}/zshrc.${_ostype}

# fpath functions
fpath=(${fpath} ${ZDOTDIR}/functions(N-/))

# function/excutable
function excutable() {
  type "$1" &> /dev/null;
}

# common environment variables
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"

# history
export HISTFILE="${ZDOTDIR}/history"
export HISTSIZE=100000
export SAVEHIST=${HISTSIZE}

# oh-my-zsh
export DISABLE_AUTO_TITLE=true

# path .bin
path=(${path} ${HOME}/.local/bin(N-/))

# direnv
if excutable direnv; then
  export DIRENV_WARN_TIMEOUT=100s
  eval "$(direnv hook zsh)"
fi

# alias
excutable colordiff && alias diff="colordiff"
excutable jq && alias jq="jq -C"
excutable ls && alias ll="ls -l"
excutable tput && alias beep="tput bel"
excutable vim && alias vi="vim"
excutable xh && alias http="xh"

# grep
if excutable grep; then
  alias grep="grep -I --color=auto"
  setopt nonomatch # for grep's glob
fi

# tmux
if excutable tmux; then
  export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
fi

# less
if excutable less; then
  export LESS="-R -F -X"
  if [[ $(excutable source-highlight-esc.sh) ]]; then
    export LESSOPEN="| source-highlight-esc.sh %s"
  fi
fi

# ansible
excutable ansible && export ANSIBLE_NOCOWS=1

# sws (ref https://sws.joseluisq.net/)
excutable sws && export SERVER_CONFIG_FILE="${XDG_CONFIG_HOME}/sws/config.toml"

# make
excutable make && export MAKEFLAGS="-j$(nproc)"

# cdr (ref http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Recent-Directories)
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

# anyframe
#
## execute-history
bindkey '^r' anyframe-widget-execute-history
#
## cdr
bindkey '^b' anyframe-widget-cdr
#
## ghq (ghq)
if excutable ghq; then
  bindkey '^g' anyframe-widget-cd-ghq-repository
fi

# historica backward/forward search with linehead string binded to ^p/^n
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# update compinit
autoload -U compinit
compinit

# docker-compose
export LOCAL_UID=$(id -u)
export LOCAL_GID=$(id -g)

# disable beep
setopt no_beep

# include local file
[[ -f ${ZDOTDIR}/zshrc.local ]] && source ${ZDOTDIR}/zshrc.local
