# include .zshrc.antigen
[[ -f ${ZDOTDIR}/zshrc.antigen ]] && source ${ZDOTDIR}/zshrc.antigen

# variables
_ostype=$(uname -s | tr '[:upper:]' '[:lower:]')

# include ostype files
[[ -f ${ZDOTDIR}/zshrc.${_ostype} ]] && source ${ZDOTDIR}/zshrc.${_ostype}

# fpath functions
[[ -d ${ZDOTDIR}/functions ]] && export FPATH="${ZDOTDIR}/functions:$FPATH"

# functions
#
function excutable() {
  type "$1" &> /dev/null;
}

# common environment variables
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"

# history
export HISTFILE="${ZDOTDIR}/history"
export HISTSIZE=100000
export SAVEHIST=${HISTSIZE}

# oh-my-zsh
export DISABLE_AUTO_TITLE=true

# path .bin
export PATH="${PATH}:${HOME}/.bin"

# direnv
if excutable direnv; then
  export DIRENV_WARN_TIMEOUT=100s
  eval "$(direnv hook zsh)"
fi

# alias
excutable ls && alias ll="ls -l"
excutable vim && alias vi="vim"
excutable gojq && alias jq="gojq -C"
excutable colordiff && alias diff="colordiff"
excutable tput && alias beep="tput bel"

# grep
if excutable grep; then
  alias grep="grep -I --color=auto"
  setopt nonomatch # for grep's glob
fi

# tmux
if excutable tmux; then
  export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
  if [[ "${_ostype}" = "darwin" ]]; then
    alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf -2 -u"
  else
    alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf"
  fi
fi

# less
if excutable less; then
  export LESS="-R -F -X"
  if [[ $(excutable source-highlight-esc.sh) ]]; then
    export LESSOPEN="| source-highlight-esc.sh %s"
  fi
fi

# ansible
excutable ansible && export ANSIBLE_NOCOWS=1

# make
excutable make && export MAKEFLAGS="-j$(nproc)"

# cdr (ref http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Recent-Directories)
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

# anyframe
#
## execute-history
bindkey '^r' anyframe-widget-execute-history
#
## cdr
bindkey '^b' anyframe-widget-cdr
#
## ghq (ghq)
if excutable ghq; then
  bindkey '^g' anyframe-widget-cd-ghq-repository
fi

# historica backward/forward search with linehead string binded to ^p/^n
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

# update compinit
autoload -U compinit
compinit

# include local file
[[ -f ${ZDOTDIR}/zshrc.local ]] && source ${ZDOTDIR}/zshrc.local
