#!/usr/bin/env bash

BIN=${1}
OPT=${2}

BINARY_FILE="direnv"
REPOSITORY="direnv/direnv"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
if [ "${ARCH}" = "x86_64" ]; then
  ARCH="amd64"
fi

DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | ${BIN}/jq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\")) | .browser_download_url")
wget ${DL_URL} -O ${OPT}/${BINARY_FILE}
chmod +x ${OPT}/${BINARY_FILE}

rm -if ${BIN}/${BINARY_FILE}
ln -s ${OPT}/${BINARY_FILE} ${BIN}/${BINARY_FILE}
