#!/usr/bin/env bash

BIN=${1}
OPT=${2}

BINARY_FILE="envsubst"
REPOSITORY="a8m/envsubst"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "${OS}" = "darwin" ]; then
  OS="Darwin"
elif [ "${OS}" = "linux" ]; then
  OS="Linux"
fi
ARCH="x86_64"

DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | ${BIN}/jq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\")) | .browser_download_url")
wget ${DL_URL} -O ${OPT}/${BINARY_FILE}
chmod +x ${OPT}/${BINARY_FILE}

rm -if ${BIN}/${BINARY_FILE}
ln -s ${OPT}/${BINARY_FILE} ${BIN}/${BINARY_FILE}
