#!/usr/bin/env bash

BIN=${1}

BINARY_FINE="gcal"
REPOSITORY="longkey1/gcal"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH="amd64"

DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | jq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\")) | .browser_download_url")
DL_FILE=$(basename ${DL_URL})
wget ${DL_URL} -O ${BIN}/${BINARY_FINE}
chmod +x ${BIN}/${BINARY_FINE}
