#!/usr/bin/env bash

BIN_DIR=$(dirname $(cd $(dirname $0); pwd))/bin
BINARY_FINE="gh"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "${OS}" = "darwin" ]; then
  OS="macOS"
fi
ARCH=$(uname -m)
if [ "${ARCH}" = "x86_64" ]; then
  ARCH="amd64"
fi
DL_URL=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | ${BIN_DIR}/gojq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\") and (test(\"(.deb$|.rpm$)\") | not)) | .browser_download_url")
ARCHIVE_FILE=$(basename ${DL_URL})
WORK_DIR=/tmp/dotfiles-${USER}-${BINARY_FINE}
ARC_OPTION="-strip-components 2"

mkdir -p ${WORK_DIR}
wget ${DL_URL} -O ${WORK_DIR}/${ARCHIVE_FILE}
${BIN_DIR}/arc ${ARC_OPTION} unarchive ${WORK_DIR}/${ARCHIVE_FILE} ${WORK_DIR}
mv ${WORK_DIR}/${BINARY_FINE} ${BIN_DIR}/${BINARY_FINE}
rm -rf ${WORK_DIR}
