#!/usr/bin/env bash

OPT=${1}
REPOSITORY="llorllale/go-gitlint"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH="amd64"
FILE="gitlint"

${OPT}/eget ${REPOSITORY} --system ${OS}/${ARCH} --file ${FILE} --to ${OPT}/
