#!/usr/bin/env bash

BIN=${1}
OPT=${2}

REPOSITORY="llorllale/go-gitlint"
FILE="gitlint"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH="amd64"

${OPT}/eget ${REPOSITORY} --system ${OS}/${ARCH} --file ${FILE} --to ${OPT}/
