#!/usr/bin/env bash

BIN=${1}
ROOTS=${2}
VERSION=${3}

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
if [ "${ARCH}" = "x86_64" ]; then
  ARCH="amd64"
fi

DL_URL=https://golang.org/dl/go${VERSION}.${OS}-${ARCH}.tar.gz
ARCHIVE_FILE=$(basename ${DL_URL})
WORK_DIR=/tmp/dotfiles-${USER}-go
ARC_OPTION="-strip-components 1"

mkdir -p ${WORK_DIR}
wget ${DL_URL} -O ${WORK_DIR}/${ARCHIVE_FILE}
${BIN}/arc ${ARC_OPTION} unarchive ${WORK_DIR}/${ARCHIVE_FILE} ${ROOTS}/${VERSION}
rm -rf ${WORK_DIR}
