#!/usr/bin/env bash

BIN=${1}

BINARY_FILE="jira"
REPOSITORY="go-jira/jira"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH="amd64"

DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | jq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\")) | .browser_download_url")
wget ${DL_URL} -O ${BIN}/${BINARY_FILE}
chmod +x ${BIN}/${BINARY_FILE}
