#!/usr/bin/env bash

BINARY_FINE="just"
REPOSITORY="casey/just"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

BIN_DIR=$(dirname $(cd $(dirname $0); pwd))/bin
DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | ${BIN_DIR}/gojq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\")) | .browser_download_url")
ARCHIVE_FILE=$(basename ${DL_URL})
WORK_DIR=/tmp/dotfiles-${USER}-${BINARY_FINE}

ARC_OPTION=""

mkdir -p ${WORK_DIR}
wget ${DL_URL} -O ${WORK_DIR}/${ARCHIVE_FILE}
${BIN_DIR}/arc ${ARC_OPTION} unarchive ${WORK_DIR}/${ARCHIVE_FILE} ${WORK_DIR}
mv ${WORK_DIR}/just-0/${BINARY_FINE} ${BIN_DIR}/${BINARY_FINE}
rm -rf ${WORK_DIR}

