#!/usr/bin/env bash

BIN=${1}

BINARY_FINE="lf"
REPOSITORY="gokcehan/lf"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
if [ "${ARCH}" = "x86_64" ]; then
  ARCH="amd64"
fi
DL_URL=$(curl -s https://api.github.com/repos/${REPOSITORY}/releases/latest | ${BIN}/gojq -r ".assets[] | select(.name | contains(\"${OS}\") and contains(\"${ARCH}\") and (test(\"(.deb$|.rpm$)\") | not)) | .browser_download_url")
ARCHIVE_FILE=$(basename ${DL_URL})
WORK_DIR=/tmp/dotfiles-${USER}-${BINARY_FINE}
ARC_OPTION=""

mkdir -p ${WORK_DIR}
wget ${DL_URL} -O ${WORK_DIR}/${ARCHIVE_FILE}
${BIN}/arc ${ARC_OPTION} unarchive ${WORK_DIR}/${ARCHIVE_FILE} ${WORK_DIR}
mv ${WORK_DIR}/${BINARY_FINE} ${BIN}/${BINARY_FINE}
rm -rf ${WORK_DIR}
