#!/usr/bin/env bash

OPT=${1}
REPOSITORY="xo/usql"

if [ "${OS}" == "linux" ]; then
  ${OPT}/eget ${REPOSITORY} --to ${OPT}/usql --asset static --file usql_static
else
  ${OPT}/eget ${REPOSITORY} --to ${OPT}/usql
fi
