#!/usr/bin/env zsh

function symlink() {
  target=${1}
  if [ -e "${HOME}/.${target}" ]; then
   echo "${HOME}/.${target} already exists"
  else
   ln -s ${ROOT}/${target} ${HOME}/.${target} && echo "${HOME}/.${target} linked"
  fi
}

function unsymlink() {
  target=${1}
  if [ -h "${HOME}/.${target}" ]; then
    unlink ${HOME}/.${target} && echo "${HOME}/.${target} unlinked"
  elif [ -e "${HOME}/.${target}" ]; then
    echo "${HOME}/.${target} not unlinked, not a symlink"
  else
    echo "${HOME}/.${target} no exists"
  fi
}

function get_bitwarden_session() {
  echo "$(cat ${DOTFILES}/bitwarden.session)"
}
