#!/usr/bin/env zsh

BIN=${1}
BINARY="eget"
WORK_DIR=/tmp/dotfiles-${USER}-$(basename ${0})

mkdir -p ${WORK_DIR}
pushd ${WORK_DIR}

curl -o eget.sh https://zyedidia.github.io/eget.sh
shasum -a 256 eget.sh
bash eget.sh
mv ${BINARY} ${BIN}/${BINARY}

popd
rm -rf ${WORK_DIR}
