#!/usr/bin/env zsh

BIN=${1}
REPOSITORY="cli/cli"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH="amd64"

if [ "${OS}" == "linux" ]; then
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/ --asset ${OS}_${ARCH}.tar.gz
elif [ "${OS}" == "darwin" ]; then
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/ --asset macOS
fi
