#!/usr/bin/env zsh

BIN=${1}
REPOSITORY="joseluisq/static-web-server"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "${OS}" == "linux" ]; then
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/sws --asset linux-musl.tar.gz
else
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/sws
fi
