#!/usr/bin/env zsh

BIN=${1}
REPOSITORY="xo/usql"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

if [ "${OS}" == "linux" ]; then
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/usql --asset static --file usql_static
else
  ${BIN}/eget ${REPOSITORY} --to ${BIN}/usql
fi
