#!/usr/bin/env zsh

BIN=${1}
REPOSITORY="mikefarah/yq"
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m | sed s/x86_64/amd64/)

${BIN}/eget ${REPOSITORY} --to ${BIN}/yq --asset ${OS}_${ARCH}.tar.gz --file yq_${OS}_${ARCH}
