#!/usr/bin/env zsh

function symlink() {
  target=${1}
  if [ -e "${HOME}/.${target}" ]; then
   echo "${HOME}/.${target} already exists"
  else
   ln -s ${ROOT}/${target} ${HOME}/.${target} && echo "${HOME}/.${target} linked"
  fi
}

function unsymlink() {
  local target=${1}
  local dest_path="${REMOTE_BIN}/$(basename ${target})"
  
  if [ -h "${dest_path}" ]; then
    unlink ${dest_path} && echo "${dest_path} unlinked"
  elif [ -e "${dest_path}" ]; then
    echo "${dest_path} not unlinked, not a symlink"
  else
    echo "${dest_path} no exists"
  fi
}

function get_bitwarden_session() {
  echo "$(cat ${SCRIPTS}/bitwarden.session)"
}

function execute_envsubst() {
  OPTION=${1}
  DESTINATION=${2}
  SOURCE=${3}
  echo "envsubst "'${OPTION}'" < ${DESTINATION} > ${SOURCE}"
  envsubst "'${OPTION}'" < ${DESTINATION} > ${SOURCE}
}

function symlink_to_symlink() {
  local target=${1}
  local source_path="${ROOT}/${target}"
  local dest_path="${REMOTE_BIN}/$(basename ${target})"
  
  if [ -e "${dest_path}" ]; then
    echo "${dest_path} already exists"
    return
  fi
  
  # 元のシンボリックリンクを指すようにする
  ln -s "${source_path}" "${dest_path}" && echo "${dest_path} linked"
}
